---
root: true
env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 13
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - '@typescript-eslint'
rules:
  'react/react-in-jsx-scope': off
  'react/prop-types': off
settings:
  react:
    version: detect
